[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2024"
name = "app"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
cortex-m = "0.7.7"
cortex-m-semihosting = "0.5.0"
log = { path = "../log" }
rt = { path = "../rt" }
