[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2024"
name = "app"
version = "0.1.0"

[dependencies]
cortex-m-semihosting = "0.3.1"
rt = { path = "../rt" }

[profile.release]
codegen-units = 1
lto = true