[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2024"
name = "app"
version = "0.1.0"

[dependencies]
cortex-m-semihosting = "0.3.1"
log = { path = "../log" }
rt = { path = "../rt" }
